name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        include:
          - os: ubuntu-latest
            artifact_name: TESTSCRT.TOS
            asset_name: TESTSCRT.TOS
            binary_name: TESTROM.BIN
    steps:  
    - name: Checkout the code
      uses: actions/checkout@v3
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install AtariST Toolkit Docker image
      run: curl -sL https://github.com/diegoparrilla/atarist-toolkit-docker/releases/download/latest/linux.sh | bash

    - name: Run - remove interactive
      run: sed -i 's/-it//' /usr/local/bin/stcmd

    - name: Run build and publish
      run: ST_WORKING_FOLDER=${GITHUB_WORKSPACE} stcmd make release

    - name: Upload the TOS file
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload shell scripts to release to latest
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: latest
        overwrite: true

    - name: Upload the TOS file
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/testrom.bin
        asset_name: testrom.bin
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload shell scripts to release to latest
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.binary_name }}
        asset_name: ${{ matrix.binary_name }}
        tag: latest
        overwrite: true
